enum UserErrorType {
  USER_DISABLED,

  LOGIN_VALID_BUT_NOT_ASSIGNED_TO_TRANSPORTER,

  /* These are used in the setup flow */
  DCC_BACKEND_HAD_SERVER_ERROR,
  DCC_BACKEND_OTP_TOKEN_ALREADY_USED,
  DCC_BACKEND_OTP_TOKEN_EXPIRED,
  DCC_BACKEND_OTP_TOKEN_WAS_WRONG,
  DCC_BACKEND_OTP_TOKEN_REJECTED_FOR_UNKNOWN_REASON,

  UNKNOWN
}
